### ISSUE TITLE
pip command failing with permissions issue

### ISSUE THREAD

**Issue by zachferr** [feederbox826/stash-s6#12]
https://github.com/feederbox826/stash-s6/blob/a94e4aea06b448789f5db63163a5812ada7a3389/stash/root/opt/entrypoint.sh#L297

While trying to get set up using this container (specifically ghcr.io/feederbox826/stash-s6:hwaccel-jf) from an existing Stash container (MIGRATE is unset as well as SKIP_CHOWN) I'm getting:

```
WARN[2024-09-06 21:33:34] /root/.stash exists, but MIGRATE is not set. Running in stashapp/stash compatibility mode
INFO[2024-09-06 21:33:34] reowning /root/
INFO[2024-09-06 21:33:34] reowning_r /root/.stash
WARN[2024-09-06 21:33:34] /root/.stash/plugins not found, skipping
WARN[2024-09-06 21:33:35] /root/.stash/scrapers not found, skipping
INFO[2024-09-06 21:33:35] Installing/upgrading python requirements...
INFO[2024-09-06 21:33:35] reowning_r /pip-install/install
INFO[2024-09-06 21:33:35] reowning_r /pip-install/cache
WARNING: The directory '/pip-install/cache' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

Starting stash...
```

At first I thought this was because I wasn't setting `/pip-install` so I added `- ./pip:/pip-install` to volumes in my docker compose but this didn't change anything. I've tried running docker compose up both with and without sudo (normally run without) with no change.

any tips? (Also thank you for this container I really appreciate all the effort!)

**Comment by feederbox826** [comment]
I also encountered this issue in my own installs but figured it was just a fluke with my volumes. I'll double check the permissions that pip wants.

**Comment by feederbox826** [comment]
Ah I see the problem now, since it's running it in migrate mode, It's chowning it to `stash:stash` but not running pipenv as `stash:stash`, but as `root:root`. Pushing a fix shortly

**Comment by feederbox826** [comment]
I just put in a fix, It was working fine in my dev environment and on my server, can you let me know if it works on yours?
