### ISSUE TITLE
plugin requirements are not getting installed

### ISSUE THREAD

**Issue by TheGlitchGal** [feederbox826/stash-s6#15]
the entrypoint script does not properly install plugin requirements

the culprit is `[ -s ... ] || [ ! -f ... ]` ([entrypoint.sh:255](https://github.com/feederbox826/stash-s6/blame/df9331a896aa2b87f383f05af615ea2674686803/stash/root/opt/entrypoint.sh#L255))

the expr translates roughly to "(exists and not empty) or not exists"; so any requirement collection done previously which results in a non empty requirements file, will make `[ -s ... ]` pass and the default requirements file gets copied over.

I assume the goal was "not exists or empty", so i propose `[ ! -f ... ] || [ ! -s ... ]`

I'll sketch-up a PR in a moment

**Comment by feederbox826** [comment]
Thanks! My bash-isms are lacking and it shows...

**Comment by TheGlitchGal** [comment]
such an icky little typo can easily happen to anyone pretty fast :joy:
