### ISSUE TITLE
install apt packages at startup

### ISSUE THREAD

**Issue by binarygeek119** [feederbox826/stash-s6#18]
there's a python pip installer it be nice to also have a apt installer.
not sure what all others would like to install by default but i like to have nano installed.
but may have more to add at a later time.

**Comment by feederbox826** [comment]
hwaccel is debiant(apt) but alpine is.. alpine

**Comment by feederbox826** [comment]
I'll throw in 
- curl
- nano
- wget 
- ncdu

as that's in my normal toolkit

**Comment by feederbox826** [comment]
adds ~7M to the image but is negligible

**Comment by feederbox826** [comment]
After looking into it more, persistence in containers isn't possible for apt, maybe I'll include it as another entrypoint script to be passed in but not for now...
