### ISSUE TITLE
Python requirements install error

### ISSUE THREAD

**Issue by fl4shforward** [feederbox826/stash-s6#20]
Hey!

While trying to install the [Filemonitor](https://github.com/stashapp/CommunityScripts/tree/main/plugins/FileMonitor) plugin I encountered the following issue:
```log
entrypoint.sh
WARN[2024-12-06 19:27:24] 🧩⚠️ COMPAT_MODE running as root since PUID/PGID missing write/ stat permissions
WARN[2024-12-06 19:27:24] 🧩 /root/.stash exists, but MIGRATE is not set. Running in COMPAT_MODE
INFO[2024-12-06 19:27:24] 🐍 Parsing /root/.stash/plugins/community/filemonitor/requirements.txt
WARN[2024-12-06 19:27:24] 🐍 /root/.stash/scrapers not found, skipping requirement search
INFO[2024-12-06 19:27:24] 🐍 Installing/upgrading python requirements...
INFO[2024-12-06 19:27:24] 🔑 fixing permissions on /pip-install/install
INFO[2024-12-06 19:27:25] 🔑 fixing permissions on /pip-install/cache
error: Couldn't parse requirement in `requirements.txt` at position 87
  Caused by: Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `#`
stashapp-tools# /root/.stash/plugins/community/filemonitor/requirements.txt
```

I investigated a little bit more, and, for some reason, on my setup, the append part of the temp requirements.txt defined here https://github.com/feederbox826/stash-s6/blob/00462860faaab8f53f84a6db4f2f2e7ee1a35c1d/stash/root/opt/entrypoint.sh#L287 https://github.com/feederbox826/stash-s6/blob/00462860faaab8f53f84a6db4f2f2e7ee1a35c1d/stash/root/opt/entrypoint.sh#L258 is made without a new line. Causing the issue when pip tries to install the reqs. As seen here:
```log
root@1c9129ca4aa0:~# cat requirements.txt 
bs4
cloudscraper
fastbencode
lxml
mechanicalsoup
pystashlib
requests
requests-toolbelt
stashapp-tools# /root/.stash/plugins/community/filemonitor/requirements.txt
stashapp-tools
pyYAML
watchdog
```

I managed to install the deps by editing the file manually and replicating the install command from the script by hand. It worked without any issue.

**Comment by feederbox826** [comment]
Thanks for looking into it! I should have a fix in soon

**Comment by massiveinvisible** [comment]
I've installed latest through Unraid and I still have this issue
