### ISSUE TITLE
ai_tagger plugin issues

### ISSUE THREAD

**Issue by binarygeek119** [feederbox826/stash-s6#21]
im having troble with the ai_tagger plugin it keeps saying this.

```

ERRO[2024-12-07 21:28:48] [Plugin / AI Tagger] Attempted to install required packages, please retry the task. 
ERRO[2024-12-07 21:28:48] Plugin returned error: exit status 1  
```

ive tryed to install the requirements.txt from within the docker.
`pip install -r requirements.txt`
but it still doesnt work after the install.
on the stock docker it works fine.

**Comment by feederbox826** [comment]
that's because the container does not use pip and it's attempting to execute it manually instead of letting the command be caught by uv

https://github.com/feederbox826/stash-s6/commit/f49272ff00b047d2ded019d122d759c2ee907cd8

**Comment by binarygeek119** [comment]
how would i get it working with uv

**Comment by feederbox826** [comment]
add it to requirements would be the best, as it's persistent but `uv pip install package` will also stopgap it until you kill the image

**Comment by binarygeek119** [comment]
ai_tagger plugin does have a requirements.txt and does install but when i go to use the plugin it it errors out like it dont have the requirements.

**Comment by binarygeek119** [comment]
it turns out it was the plugin with asyncio causing issues
