### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by rastarr** [feederbox826/stash-s6#6]
Stumbled across mention of your docker image in the Discord and have a few questions.
I'm wanting to better utilise scrapers and contribute back but looks like my Synology based docker image is missing Python libraries.

1. Does this image enable shell access inside the container?
2. What does the the MIGRATE variable do and what are/is the parameters? I'm currently using stashapp/stash
3. Same for SKIP_CHOWN. parameters? What does this even do?
4. For hwaccel, am I needing to add ' :hwaccel ' to the compose file with the image name?

Sorry for the dumb newbie questions. I don't want to screw anything up here :)

**Comment by feederbox826** [comment]
1. Shell access is always enabled, this does not add any functionality for that
2. MIGRATE looks for a value of `TRUE` - this is to migrate between stash and stash-s6
3. `SKIP_CHOWN` also looks for `TRUE` - this is to skip fixing permissions for mounted files
4. yes, pretty much
