### ISSUE TITLE
New installation needs to create venv at `/pip-install/venv`

### ISSUE THREAD

**Issue by Johbii** [feederbox826/stash-s6#7]
Tracking this as I ran into this when running myself.

Creation of the python virtual environment folder with proper permissions should happen on initialization for a fresh install.

If you manually create the folder at `/pip-install/venv` it works.

**Comment by feederbox826** [comment]
Now it should mkdir and chown the /cache and /venv directories, I'll add another check to make sure the root path gets the proper perms as well
