### ISSUE TITLE
Intel ARC testing

### ISSUE THREAD

**Issue by feederbox826** [feederbox826/stash-s6#8]
I have tested most other hardware accelerations, I am just missing Intel ARC. I have no reason to believe they should not work, but it would be nice to have validation :)

Thanks @nerethos for testing V4L2 ❤️

**Comment by nerethos** [comment]
Raspberry Pi 4b

![firefox_kHi9VnlxgV](https://github.com/feederbox826/stash-s6/assets/19306850/17ab99ad-6333-4599-a73f-1134a5079177)

**Comment by MDKAOD** [comment]
Arc A380

```
INFO[2024-06-29 15:36:25] [InitHWSupport] Supported HW codecs [3]:
        h264_qsv
        h264_vaapi
        vp9_vaapi
```

Sometimes works. Doesn't do anything for direct play, as expected. Arc not used for preview generation. GPU preview generation was a big ask on the main branch, and the thread is confusing if it's supposed to work or not, but it does not appear to work here, and I was never able to get it to work at all with the original project. 

Errors with video freeze below. Video appears to continue to work when unpaused. Full disclosure, I had difficulty converting over from the main project, so this could be container corruption or something.

`
2024-06-29T15:49:56.444149742-04:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"<SANITIZED>","requestID":"301e0ea9f378/ffw7KI0Djx-000898","requestMethod":"GET","requestPath":"/scene/17282/stream.mp4","requestURL":"<SANITIZED>/scene/17282/stream.mp4?resolution=FOUR_K"} httpResponse={"bytes":2327810,"elapsed":1668.903091,"status":200} service=stash
ERRO[2024-06-29 15:49:56] [transcode] ffmpeg error when running command </usr/bin/ffmpeg -hide_banner -v error -hwaccel qsv -hwaccel_output_format qsv -i /data/SiteRips/[Patreon] AMWednesday/Add Ons/WebRip/2160p_29.97002997002997_14872kbps(3840x2160).mp4 -c:v h264_qsv -global_quality 20 -preset faster -movflags frag_keyframe+empty_moov -vf scale_qsv=-1:1920 -an -f mp4 pipe:>: libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0 
`

Also:

`2024-06-29T15:50:43.685301829-04:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"<SANITIZED>","requestID":"301e0ea9f378/ffw7KI0Djx-000907","requestMethod":"POST","requestPath":"/graphql","requestURL":"<SANITIZED>/graphql"} httpResponse={"bytes":59,"elapsed":12.262026,"status":200} service=stash
ERRO[2024-06-29 15:50:43] [transcode] ffmpeg error when running command </usr/bin/ffmpeg -hide_banner -v error -hwaccel qsv -hwaccel_output_format qsv -ss 20.078476000000002 -i /data/SiteRips/<SANITIZED>.mp4 -c:v h264_qsv -global_quality 20 -preset faster -movflags frag_keyframe+empty_moov -vf scale_qsv=-1:1920 -an -f mp4 pipe:>: libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0 
ERRO[2024-06-29 15:50:43] [transcode] error transcoding video file: context canceled 
2024-06-29T15:50:43.884187128-04:00 WRN Response: 400 Client Error httpRequest={"proto":"HTTP/1.1","remoteIP":"<SANITIZED>","requestID":"301e0ea9f378/ffw7KI0Djx-000908","requestMethod":"GET","requestPath":"/scene/17282/stream.mp4","requestURL":"<SANITIZED>/scene/17282/stream.mp4?resolution=FOUR_K\u0026start=6835.162239583333"} httpResponse={"bytes":16,"elapsed":209.246499,"status":400} service=stash
ERRO[2024-06-29 15:50:44] [transcode] ffmpeg error when running command </usr/bin/ffmpeg -hide_banner -v error -hwaccel qsv -hwaccel_output_format qsv -ss 6835.162239583333 -i /data/SiteRips/<SANITIZED>.mp4 -c:v h264_qsv -global_quality 20 -preset faster -movflags frag_keyframe+empty_moov -vf scale_qsv=-1:1920 -an -f mp4 pipe:>: libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0 `

**Comment by feederbox826** [comment]
Thanks for the report! It does seem to be struggling with libva, will dive into that

**Comment by nerethos** [comment]
> ```
> 2024-06-29T15:49:56.444149742-04:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"<SANITIZED>","requestID":"301e0ea9f378/ffw7KI0Djx-000898","requestMethod":"GET","requestPath":"/scene/17282/stream.mp4","requestURL":"<SANITIZED>/scene/17282/stream.mp4?resolution=FOUR_K"} httpResponse={"bytes":2327810,"elapsed":1668.903091,"status":200} service=stash
> ERRO[2024-06-29 15:49:56] [transcode] ffmpeg error when running command </usr/bin/ffmpeg -hide_banner -v error -hwaccel qsv -hwaccel_output_format qsv -i /data/SiteRips/[Patreon] AMWednesday/Add Ons/WebRip/2160p_29.97002997002997_14872kbps(3840x2160).mp4 -c:v h264_qsv -global_quality 20 -preset faster -movflags frag_keyframe+empty_moov -vf scale_qsv=-1:1920 -an -f mp4 pipe:>: libva info: VA-API version 1.21.0
> libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
> libva info: Found init function __vaDriverInit_1_21
> libva info: va_openDriver() returns 0
> libva info: VA-API version 1.21.0
> libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
> libva info: Found init function __vaDriverInit_1_21
> libva info: va_openDriver() returns 0 
> ```

I'm also seeing the above when using my i3-12100, but the transcodes are definitely working. The error seems to occur when ffmpeg has finished the transcode. FWIW I get the same thing with the testing branch on my docker image, which also uses jellyfin-ffmpeg6.

**Comment by feederbox826** [comment]
yeah, iirc iHD is the old <g8 driver, which means for some reason it's not using the qsv drivers. returns 0 means nothing went wrong, I think it could also be a pipe problem

**Comment by musicderp** [comment]
Hey, just got an arc a380 and I guess this is as good a place as any to say I can't get it to work.
Running in stash compatibility mode:
`INFO[2024-07-14 09:36:53] [InitHWSupport] Supported HW codecs [0]:     
INFO[2024-07-14 09:36:53] stash version: v0.26.2-49-g720b233b - Official Build - 2024-07-04 01:42:12 
INFO[2024-07-14 09:36:53] stash is listening on 0.0.0.0:9999           
INFO[2024-07-14 09:36:53] stash is running at http://localhost:9999/   
INFO[2024-07-14 09:36:54] Version v0.26.2-49-g720b233b (720b233b) is already the latest released `

My compose passes in /dev/dri:/dev/dri. My kernel version is 6.8.0-38-generic running ubuntu 24.04 and docker 27.0.3. 
I have validated that this configuration does work with plex. I don't know if this is a permissions thing, but here is what LSIO does to get it to work with plex: https://github.com/linuxserver/docker-plex/blob/master/root/etc/s6-overlay/s6-rc.d/init-plex-gid-video/run

For what it's worth, I also attempted to add this to my docker compose to no avail:

`    group_add:
      - "109"
      - "44"`

I am running `ghcr.io/feederbox826/stash-s6:hwaccel-jf-develop` of your container. Let me know if I can get you any other information or logs to see what's going on here!

Thanks!

**Comment by feederbox826** [comment]
> but here is what LSIO does to get it to work with plex

ah, those are the default video_id group names for the /dev/dri mount. I remember them being slightly different, but that might be NVIDIA. nerethos also recommends something similar. I'll try with a hotfix for now, and try to validate once my card comes in

**Comment by feederbox826** [comment]
Got my ARC, working through the issues right now but it's mostly to do with permissions and drivers 😅

**Comment by MDKAOD** [comment]
How can we help? I'm running s6 on unraid.

**Comment by feederbox826** [comment]
I'll get my setup stabilized and tested first, I might need some cross-checks for unraid because of driver differences, I'll let you know

Thanks ❤️

**Comment by feederbox826** [comment]
Still having some issues with preview generation running out of range, will publish docs on driver installation from intel side and group IDs

**Comment by feederbox826** [comment]
ARC seems stable atm, with just a few config tweaks and `group_add` - please let me know if this doesn't work on UnRAID, I have no idea of the driver situation on that end

**Comment by MDKAOD** [comment]
> Still having some issues with preview generation running out of range, will publish docs on driver installation from intel side and group IDs

[https://github.com/0x90d/videoduplicatefinder?tab=readme-ov-file ](VideoDuplicateFinder) may have some hints here. It uses a clever ffmpeg call to generate screenshots then some way to compare them (I'm not sure of the exact mechanism), but it uses hwaccel and works well.

**Comment by nerethos** [comment]
> How can we help? I'm running s6 on unraid. 

Are you running the Unraid 7.x beta? The stable version doesn't have the kernel drivers for Arc

**Comment by MDKAOD** [comment]
I'm using the thor kernel on v6. I haven't upgraded to 7 beta yet. https://github.com/thor2002ro/unraid_kernel

**Comment by MDKAOD** [comment]
> I'm using the thor kernel on v6. I haven't upgraded to 7 beta yet. https://github.com/thor2002ro/unraid_kernel



> > How can we help? I'm running s6 on unraid.
> 
> Are you running the Unraid 7.x beta? The stable version doesn't have the kernel drivers for Arc

I'm using the thor kernel on v6. I haven't upgraded to 7 beta yet. https://github.com/thor2002ro/unraid_kernel

**Comment by MDKAOD** [comment]
> ARC seems stable atm, with just a few config tweaks and `group_add` - please let me know if this doesn't work on UnRAID, I have no idea of the driver situation on that end

No apparent issues while running on the thor kernel. I haven't upgraded to official, but I don't anticipate issues.
